# Generated by Django 5.1.3 on 2024-11-12 19:53

import datetime
import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=255, verbose_name='Traffic Start Address')),
                ('traffic_start_point', location_field.models.plain.PlainLocationField(default='', max_length=63)),
                ('end_address', models.CharField(default='', max_length=255, verbose_name='Traffic End Address')),
                ('traffic_end_point', location_field.models.plain.PlainLocationField(default='', max_length=63)),
                ('spot_type', models.CharField(choices=[('Turn', 'Turn'), ('Main Street/High Street', 'Main Street/High Street'), ('Bystreet', 'Bystreet')], max_length=50)),
                ('traffic_level', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], default='High', max_length=50)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Appeared In')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('potential_factors', models.ManyToManyField(blank=True, to='Traffic_Spots.potentialfactor')),
            ],
        ),
    ]
