# Generated by Django 5.1.3 on 2024-11-05 20:30

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
