# Generated by Django 5.1.3 on 2024-11-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favorites', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelocation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Alternate Name'),
        ),
    ]
