# Generated by Django 5.1.3 on 2024-11-05 20:30

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('start_location', location_field.models.plain.PlainLocationField(default='', max_length=63)),
                ('end_location', location_field.models.plain.PlainLocationField(default='', max_length=63)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('traffic_data_source', models.CharField(choices=[('Google Maps', 'Google Maps'), ('OpenStreetMap', 'OpenStreetMap')], max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
