# Generated by Django 5.1.3 on 2024-11-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='route',
            name='start_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
