# Generated by Django 5.1.3 on 2024-11-12 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Traffic_Spots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('traffic_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Traffic_Spots.trafficspot')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_level', models.IntegerField()),
                ('analysis_summary', models.TextField()),
                ('recommendations_summary', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('factors', models.ManyToManyField(blank=True, to='Traffic_Spots.potentialfactor')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('traffic_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Traffic_Spots.trafficspot')),
            ],
        ),
    ]
